// Runtime extensions to the transaction types
// These properties are added at runtime but not part of the database schema

import { TransactionWithCategory } from "@shared/schema";

declare module "@shared/schema" {
  interface TransactionWithCategory {
    // Flag indicating if this is a recurring instance (generated by the client)
    isRecurringInstance?: boolean;
    
    // The display date for this instance (may differ from the base transaction date)
    displayDate?: string | Date;
    
    // The string representation of the display date (for consistent keys)
    displayDateStr?: string;
    
    // Whether this transaction should be counted in budget calculations
    shouldCount?: boolean;
    
    // Whether this transaction is in the past
    isInPast?: boolean;
    
    // Whether this transaction is in the currently viewed month
    isInMonth?: boolean;
  }
}